name: CI
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga proyecto
        uses: actions/checkout@v3
      - name: Instalacion Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Permisos de ejecucion Gradle
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build